### ISSUE TITLE
incompatible some packages?

### ISSUE THREAD

**Issue by dyseo** [Workiva/frugal#1114]
after i've install `frugal` from `pip` i got this message ```ERROR: beckett 0.8.0 has requirement requests==2.10.0, but you'll have requests 2.12.5 which is incompatible.```

and ```ERROR: frugal 2.13.1 has requirement thrift==0.10.0, but you'll have thrift 0.11.0 which is incompatible.```

what happened if i use lasted packages and use frugal?
i know frugal need packages from that version require, but i want too use lasted version from that packages

im so appreciate for any answered

**Comment by yuanmwang-wf** [comment]
thrift 0.11.0 has some breaking changes for frugal, so you'll need to use `thrift==0.10.0`. 

Also looks like you're using an old version of frugal (2.13.1)? I think you can try the latest version of frugal (there's no breaking change for python between 2.x and 3.x).

**Comment by dyseo** [comment]
@yuanmwang-wf lasted version of frugal? i just see [frugal 2.13.1](https://pypi.org/project/frugal/) from pypi, how make sure i got lasted version of frugal?

**Comment by yuanmwang-wf** [comment]
ok, sorry that looks like our problem - the latest version of frugal should be 3.3.2 but looks like no version beyond 2.13.1 were pushed to public pypi, we'll look into it this week.

**Comment by dyseo** [comment]
@yuanmwang-wf thanks for that, make sure this package on pypi for easly documented and any 
now i'll try that lasted version
