### ISSUE TITLE
Frugal generates `==` operator incorrectly

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/frugal#1163]
#### Ultimate Problem
Generated dart code is comparing lists with `==` operator. This means that anything that uses a frugal list cannot be compared in dart.

#### Suggested Fix
Lists in dart can't be compared with `==` and instead need to use `listsEqual()`

#### Example
For this frugal struct

```thrift
struct ConceptSearchRequest {
  ...
  3: optional list<string> conceptTypes
  ...
}
```

the corresponding dart `==` operator looks like:

```dart
@override
  bool operator ==(Object o) {
    if (o is ConceptSearchRequest) {
      return ...
        this.conceptTypes == o.conceptTypes && // ERROR IN THIS LINE
        ...
    }
    return false;
  }
```

**Comment by yuanmwang-wf** [comment]
Fixed in https://github.com/Workiva/frugal/releases/tag/3.5.1
