### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by tylertreat** [Workiva/frugal#902]
Looks like the automated release notes haven't been working since 2.4.0. Would be nice if release notes were included, especially now that this is open source.

**Comment by aldenpeterson-wf** [comment]
They are generated and included on the release PRs, but they do need to be manually added to the release unfortunately...

ie see:

https://github.com/Workiva/frugal/pull/901

**Comment by tylertreat** [comment]
Would it be feasible to automate it?

**Comment by brianshannan-wf** [comment]
I made a ticket for one of our internal teams to add this feature, in the mean time I added release notes to releases so they should be up to date

**Comment by aldenpeterson-wf** [comment]
I have bender configured to at least put them in the release PR so if you click into the PR (which does go to the release notes) it's there.
