### ISSUE TITLE
nats: no servers available for connection

### ISSUE THREAD

**Issue by 13o6** [Workiva/frugal#947]
I'm trying to run the `nats` Go example and managed to build it, but when I'm trying to run it I get the following panic: 
```bash
panic: nats: no servers available for connection

goroutine 1 [running]:
main.main()
	.../src/frugal/server/main.go:22 +0x17f

```
I skimmed through  [go-nats/nats.go](https://github.com/nats-io/go-nats/blob/6f06d34c19fc8607adf14668b5bb2c9465d78348/nats.go) but couldn't find what's the reason behind the error.
Any hints are much appreciated!

Note:
I've changed the now deprecated [1] `nats.DefaultOptions` to `nats.GetDefaultOptions()`

[1] - https://github.com/nats-io/go-nats/pull/308

**Comment by tylertreat** [comment]
Do you have a NATS server running?

**Comment by 13o6** [comment]
Thanks @tylertreat - forgot about that...

**Comment by 13o6** [comment]
One follow-up @tylertreat - I now get the following: 
```
request: stateless NATS service TTransport not open
```
which after some digging[1,2] I discovered that the cause may be the transport connection not being open. However, I don't fully understand why since I check, as in th example, for the transport being open *long before* the provider is being used in creating a client, and the client then used for the RPC call. Snippet of the check right after creating the transport.
```go 
		natsOptions := nats.GetDefaultOptions()
		conn, err := natsOptions.Connect()
		if err != nil {
			panic(err)
		}
		natsTransport := frugal.NewFNatsTransport(conn, "my-service", "service-abc")
		defer natsTransport.Close()
		if err := natsTransport.Open(); err != nil {
			panic(err)
		}
```

[1] - https://github.com/Workiva/frugal/blob/e5df46bf7f7c38ab267b3080f5ee0b384702bead/lib/go/nats_transport.go#L185
[2] - https://github.com/Workiva/frugal/blob/e5df46bf7f7c38ab267b3080f5ee0b384702bead/lib/go/nats_transport.go#L146

**Comment by 13o6** [comment]
Nevermind, I identified and fixed the issue in my code. Thanks!
